version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.15.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint:ci
      - run:
          name: pre-danger
          command: git config user.email "decrapifier@govspend.us" && git config user.name "Decrapifier" && git config push.default upstream && git branch -u origin/$CIRCLE_BRANCH
          when: always
      - run:
          name: danger
          command: npm run duti
          when: always
      -run:
          name: build
          command: npm build
      - deploy:
          name: Maybe Deploy react-social-auth
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              npm publish || true
            fi
